module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    HOSTEL_MANAGER: "HOSTEL_MANAGER",
  },
  USER_TYPE: {
    BUSINESS: "BUSINESS",
    INDIVIDUAL: "INDIVIDUAL",
    USER: "USER",
  },
  RIDE_STATUS: {
    AVAILABLE: "AVAILABLE",
    UNAVAILABLE: "UNAVAILABLE",
  },
  TRIP_STATUS: {
    BOOKED: "BOOKED",
    BOARDED: "BOARDED",
    COMPLETED: "COMPLETED",
  },
};
